### ISSUE TITLE
проблема с tetris_windows (Windows) | решено

### ISSUE THREAD

**Issue by secret404** [Catalyst-42/Tetris#1]
Сразу скажу что c++ я не знаю АБСОЛЮТНО (по этому возможно эта ошибка из-за Компилятора g++ которым я пользовался), а тут я чтобы поиграть в тетрис и посмотреть сто создал Catalyst-42.

У меня возникла вот эта ошибка

tetris_window=.cpp: In function 'void coutField()':
tetris_window=.cpp:163:43: error: cannot convert 'wchar_t*' to 'LPCSTR' {aka 'const char*'}
  163 |     WriteConsoleOutputCharacter(hConsole, screen_buffer, ScreenX * ScreenY, { 0,0 }, &dwBytesWritten);
      |                                           ^~~~~~~~~~~~~
      |                                           |
      |                                           wchar_t*
In file included from C:/msys64/ucrt64/include/windows.h:74,
                 from tetris_window=.cpp:2:
C:/msys64/ucrt64/include/wincon.h:228:87: note:   initializing argument 2 of 'WINBOOL WriteConsoleOutputCharacterA(HANDLE, LPCSTR, DWORD, COORD, LPDWORD)'
  228 |   WINBASEAPI WINBOOL WINAPI WriteConsoleOutputCharacterA(HANDLE hConsoleOutput,LPCSTR lpCharacter,DWORD nLength,COORD dwWriteCoord,LPDWORD lpNumberOfCharsWritten);
      |                                                                                ~~~~~~~^~~~~~~~~~~

Я смог вроде найти решение (мне помогло) и оставляю его тут для других
что изменил ?
WriteConsoleOutputCharacter(hConsole, screen_buffer, ScreenX * ScreenY, { 0,0 }, &dwBytesWritten); 
на
WriteConsoleOutputCharacterW(hConsole, screen_buffer, ScreenX * ScreenY, { 0,0 }, &dwBytesWritten);

**Comment by Catalyst-42** [comment]
Хорошо, спасибо, добавим ваше решение как quick fix для g++, потому что для моего Visual Studio такой код тоже работает исправно.
